[package]
authors = ["[your_name] <[your_email]>"]
edition = "2018"
name = "flipper"
version = "0.1.0"

[dependencies]
ink_abi = {version = "2", git = "https://github.com/paritytech/ink", tag = "latest-v2", package = "ink_abi", default-features = false, features = ["derive"], optional = true}
ink_core = {version = "2", git = "https://github.com/paritytech/ink", tag = "latest-v2", package = "ink_core", default-features = false}
ink_lang = {version = "2", git = "https://github.com/paritytech/ink", tag = "latest-v2", package = "ink_lang", default-features = false}
ink_primitives = {version = "2", git = "https://github.com/paritytech/ink", tag = "latest-v2", package = "ink_primitives", default-features = false}

scale = {package = "parity-scale-codec", version = "1.2", default-features = false, features = ["derive"]}

[dependencies.type-metadata]
default-features = false
features = ["derive"]
git = "https://github.com/type-metadata/type-metadata.git"
optional = true
rev = "02eae9f35c40c943b56af5b60616219f2b72b47d"

[lib]
crate-type = [
  "cdylib", # Used for normal contract Wasm blobs.
  "rlib", # Required for ABI generation, and using this contract as a dependency. If using `cargo contract build`, it will be automatically disabled to produce a smaller Wasm binary
]
path = "lib.rs"

[features]
default = ["test-env"]
ink-as-dependency = []
ink-generate-abi = [
  "std",
  "ink_abi",
  "type-metadata",
  "ink_core/ink-generate-abi",
  "ink_lang/ink-generate-abi",
]
std = [
  "ink_abi/std",
  "ink_core/std",
  "ink_primitives/std",
  "scale/std",
  "type-metadata/std",
]
test-env = [
  "std",
  "ink_lang/test-env",
]
