[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
name = "abi-gen"
publish = false
version = "0.1.0"

[[bin]]
name = "abi-gen"
path = "main.rs"

[dependencies]
contract = {path = "../../contracts/flipper", package = "flipper", default-features = false, features = ["ink-generate-abi"]}
ink_lang = {version = "2", git = "https://github.com/paritytech/ink", tag = "latest-v2", package = "ink_lang", default-features = false, features = ["ink-generate-abi"]}
serde = "1.0"
serde_json = "1.0"
