[package]
authors = ["[your_name] <[your_email]>"]
edition = "2018"
name = "flipper"
version = "0.1.0"

[dependencies]
ink_core = {git = "https://github.com/paritytech/ink", branch = "master", package = "ink_core", default-features = false}
ink_lang = {git = "https://github.com/paritytech/ink", branch = "master", package = "ink_lang", default-features = false}
ink_metadata = {git = "https://github.com/paritytech/ink", branch = "master", package = "ink_metadata", default-features = false, features = ["derive"], optional = true}
ink_primitives = {git = "https://github.com/paritytech/ink", branch = "master", default-features = false}

scale = {package = "parity-scale-codec", version = "1.3", default-features = false, features = ["derive"]}
scale-info = {version = "0.3", default-features = false, features = ["derive"], optional = true}

[lib]
crate-type = [
  "cdylib",
  "rlib",
]
path = "lib.rs"

[features]
default = ["std"]
ink-as-dependency = []
std = [
  "ink_metadata/std",
  "ink_core/std",
  "ink_primitives/std",
  "scale/std",
  "scale-info/std",
]

[profile.release]
lto = true
opt-level = "z"
overflow-checks = true
panic = "abort"
